import type { Difficulty, GradeLevel, GradedActivity, Subject } from './types.ts';

const slug = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
const base = (grade: GradeLevel, subject: Subject, id: string, topic: string, skillDescription: string, token: string, difficulty: Difficulty) => ({
  id: `grade-${grade}-${subject}-extension-${id}`, grade, subject, topic, skillId: `${grade}-${subject}-${slug(topic)}`,
  skillDescription, token, difficulty, assessmentEligible: true, activity: `${topic} challenge`,
});
const mc = (grade: GradeLevel, subject: Subject, id: string, topic: string, skill: string, token: string, difficulty: Difficulty, prompt: string, answer: string, distractors: [string, string], hint: string, explanation: string): GradedActivity => ({ ...base(grade, subject, id, topic, skill, token, difficulty), activityType: 'multiple-choice', prompt, answer, choices: [answer, ...distractors], hint, explanation });
const tf = (grade: GradeLevel, subject: Subject, id: string, topic: string, skill: string, token: string, difficulty: Difficulty, prompt: string, answer: boolean, hint: string, explanation: string): GradedActivity => ({ ...base(grade, subject, id, topic, skill, token, difficulty), activityType: 'true-false', prompt, answer, hint, explanation });
const numeric = (grade: GradeLevel, subject: Subject, id: string, topic: string, skill: string, token: string, difficulty: Difficulty, prompt: string, answer: number, hint: string, explanation: string, suffix?: string, tolerance?: number): GradedActivity => ({ ...base(grade, subject, id, topic, skill, token, difficulty), activityType: 'numeric', prompt, answer, hint, explanation, suffix, tolerance });
const order = (grade: GradeLevel, subject: Subject, id: string, topic: string, skill: string, token: string, difficulty: Difficulty, prompt: string, correctOrder: string[], hint: string, explanation: string): GradedActivity => ({ ...base(grade, subject, id, topic, skill, token, difficulty), activityType: 'ordering', prompt, items: [...correctOrder], correctOrder, hint, explanation });

export const gradeExtensions: Partial<Record<GradeLevel, Record<Subject, GradedActivity[]>>> = {
  '9': {
    science: [
      mc('9', 'science', 'cell-energy-1', 'Cell biology', 'Explain how cell structures support energy use.', 'ATP', 2, 'Which organelle transfers energy from food into ATP in most eukaryotic cells?', 'Mitochondrion', ['Nucleus', 'Cell wall'], 'Look for the organelle associated with cellular respiration.', 'Mitochondria carry out major stages of cellular respiration and produce most cellular ATP.'),
      tf('9', 'science', 'cell-energy-2', 'Cell biology', 'Connect photosynthesis and cellular respiration.', '↻', 2, 'True or false: The products of photosynthesis can become reactants in cellular respiration.', true, 'Compare glucose and oxygen in the two processes.', 'Photosynthesis produces glucose and oxygen, which cells can use during cellular respiration.'),
      mc('9', 'science', 'genetics-1', 'Heredity', 'Use allele combinations to reason about inherited traits.', 'Aa', 2, 'If A is dominant, which genotype is heterozygous?', 'Aa (one of each)', ['AA (two dominant alleles)', 'aa (two recessive alleles)'], 'Heterozygous means the two alleles differ.', 'Aa contains two different alleles, so it is heterozygous.'),
      tf('9', 'science', 'genetics-2', 'Heredity', 'Distinguish genes, alleles, and environment.', 'DNA', 3, 'True or false: Every observable trait is controlled by exactly one gene and never affected by the environment.', false, 'Many traits have more than one influence.', 'Many traits involve multiple genes, environmental conditions, or both.'),
      mc('9', 'science', 'ecology-1', 'Ecology', 'Analyze energy transfer through ecosystems.', '10%', 2, 'Why is less energy available at higher trophic levels?', 'Organisms use and release much energy before it transfers', ['Energy is destroyed by predators', 'Producers contain no chemical energy'], 'Think about metabolism and heat at each level.', 'Organisms use energy for life processes, and much is transferred to the surroundings as heat.'),
      order('9', 'science', 'ecology-2', 'Ecology', 'Trace ecological organization from small to large scales.', '🌿', 2, 'Order these ecological levels from smallest to largest.', ['Organism', 'Population', 'Community', 'Ecosystem'], 'Begin with one individual living thing.', 'Individuals form populations; interacting populations form communities within ecosystems.'),
    ],
    math: [
      numeric('9', 'math', 'linear-1', 'Linear equations', 'Solve multi-step linear equations.', 'x', 2, 'Solve 3x + 7 = 25. What is x?', 6, 'Subtract 7 before dividing by 3.', '3x = 18, so x = 6.'),
      mc('9', 'math', 'linear-2', 'Linear equations', 'Interpret slope and intercept in context.', 'y=mx+b', 2, 'In y = 4x + 3, what does 4 represent?', 'The slope', ['The y-intercept', 'The x-intercept'], 'Compare the equation with y = mx + b.', 'The coefficient m is the slope, so the slope is 4.'),
      numeric('9', 'math', 'systems-1', 'Systems of equations', 'Solve a system using substitution or elimination.', '∩', 3, 'For y = x + 2 and y = 8 − x, what is the x-coordinate of the intersection?', 3, 'Set the two expressions for y equal.', 'x + 2 = 8 − x gives 2x = 6, so x = 3.'),
      tf('9', 'math', 'systems-2', 'Systems of equations', 'Interpret solutions to systems graphically.', '∥', 2, 'True or false: Two distinct parallel lines have no solution as a system.', true, 'A solution is a point shared by both lines.', 'Distinct parallel lines never intersect, so the system has no solution.'),
      mc('9', 'math', 'functions-1', 'Functions', 'Identify functions from input-output rules.', 'f(x)', 2, 'Which relation is not a function?', 'One input maps to two different outputs', ['Each input maps to one output', 'Different inputs share one output'], 'A function assigns exactly one output to each input.', 'A relation fails to be a function when one input has more than one output.'),
      numeric('9', 'math', 'functions-2', 'Functions', 'Evaluate a function for a given input.', 'f(4)', 2, 'If f(x) = 2x² − 1, what is f(4)?', 31, 'Substitute 4 for x before subtracting 1.', '2(4²) − 1 = 32 − 1 = 31.'),
    ],
    english: [
      mc('9', 'english', 'evidence-1', 'Textual evidence', 'Select evidence that directly supports an inference.', '“ ”', 2, 'Which evidence best supports the inference that Mara is nervous before speaking?', 'She rereads her notes and takes three slow breaths.', ['The room has twenty chairs.', 'Her speech is about local parks.'], 'Choose the detail that reveals an emotional state.', 'Repeated checking and controlled breathing directly suggest nervousness.'),
      tf('9', 'english', 'evidence-2', 'Textual evidence', 'Distinguish evidence from unsupported opinion.', '⌕', 2, 'True or false: Strong literary analysis connects a claim to specific details from the text.', true, 'A claim needs support a reader can verify.', 'Specific textual evidence makes an interpretation clear and supportable.'),
      mc('9', 'english', 'argument-1', 'Argument', 'Distinguish claims, reasons, and evidence.', '→', 2, 'Which statement is a claim rather than evidence?', 'The city should add more protected bike lanes.', ['A traffic count recorded 430 cyclists Tuesday.', 'The report lists five collision locations.'], 'A claim states a position that reasons and evidence can support.', 'The bike-lane statement proposes a position; the other statements report evidence.'),
      order('9', 'english', 'argument-2', 'Argument', 'Organize an evidence-based paragraph.', '¶', 2, 'Order the parts of a focused argument paragraph.', ['Claim', 'Relevant evidence', 'Reasoning that connects the evidence', 'Concluding insight'], 'Begin with the point the paragraph will support.', 'A clear paragraph states a claim, supports it, explains the connection, and concludes.'),
      mc('9', 'english', 'sources-1', 'Source credibility', 'Evaluate the credibility and relevance of sources.', '✓', 3, 'Which source is strongest for a current claim about regional water quality?', 'A recent report with methods and data from the regional water agency', ['An anonymous undated comment', 'A fictional story set near a river'], 'Look for relevant expertise, current evidence, and transparent methods.', 'The agency report is directly relevant and provides methods and evidence that can be checked.'),
      tf('9', 'english', 'sources-2', 'Source credibility', 'Recognize the need to verify online information.', 'www', 2, 'True or false: A polished webpage is automatically reliable even when it gives no author or evidence.', false, 'Design quality and evidence quality are different.', 'Credibility depends on authorship, evidence, purpose, currency, and corroboration—not appearance alone.'),
    ],
  },
  '10': {
    science: [
      mc('10', 'science', 'atoms-1', 'Atomic structure', 'Relate atomic number to subatomic particles.', 'Z', 2, 'What determines an element’s atomic number?', 'Its number of protons', ['Its number of neutrons', 'Its total number of bonds'], 'The atomic number identifies the element.', 'Each element is defined by the number of protons in its nuclei.'),
      numeric('10', 'science', 'atoms-2', 'Atomic structure', 'Use mass and atomic numbers to determine neutrons.', 'n⁰', 2, 'An atom has mass number 23 and atomic number 11. How many neutrons does it have?', 12, 'Subtract the proton count from the mass number.', '23 − 11 = 12 neutrons.'),
      tf('10', 'science', 'reactions-1', 'Chemical reactions', 'Apply conservation of matter to reactions.', '⇌', 2, 'True or false: In a closed system, atoms are rearranged but conserved during a chemical reaction.', true, 'Track the atoms before and after the reaction.', 'Chemical reactions rearrange atoms; they do not create or destroy them in ordinary closed-system reactions.'),
      mc('10', 'science', 'reactions-2', 'Chemical reactions', 'Identify evidence of chemical change.', 'Δ', 2, 'Which observation most strongly supports that a chemical reaction occurred?', 'A new gas forms when two solutions mix', ['Ice changes shape while melting', 'Salt disappears into water'], 'Look for evidence that a new substance formed.', 'Unexpected gas formation can indicate new substances were produced.'),
      mc('10', 'science', 'climate-1', 'Climate systems', 'Distinguish weather from climate evidence.', 'CO₂', 3, 'Which dataset is most useful for identifying a long-term climate trend?', 'Average temperature records collected consistently for many decades', ['One unusually hot afternoon', 'A seven-day forecast'], 'Climate describes patterns over long periods.', 'Consistent multi-decade records can reveal long-term trends beyond short-term weather variation.'),
      tf('10', 'science', 'climate-2', 'Climate systems', 'Explain the greenhouse effect using energy transfer.', 'IR', 3, 'True or false: Greenhouse gases absorb and re-emit some infrared energy in Earth’s atmosphere.', true, 'Consider the energy Earth emits after absorbing sunlight.', 'Greenhouse gases interact with outgoing infrared radiation and affect atmospheric energy balance.'),
    ],
    math: [
      numeric('10', 'math', 'geometry-1', 'Similarity and geometry', 'Apply scale factors to similar figures.', '△', 2, 'Two similar triangles have a scale factor of 3. A corresponding side on the smaller triangle is 5. What is the larger side?', 15, 'Multiply the corresponding length by the scale factor.', '5 × 3 = 15.'),
      mc('10', 'math', 'geometry-2', 'Similarity and geometry', 'Use angle relationships in parallel-line diagrams.', '∠', 2, 'When parallel lines are cut by a transversal, corresponding angles are what?', 'Congruent', ['Always supplementary', 'Unrelated'], 'Picture angles in matching corners.', 'Corresponding angles formed by a transversal of parallel lines have equal measures.'),
      numeric('10', 'math', 'quadratic-1', 'Quadratic relationships', 'Solve a factorable quadratic equation.', 'x²', 3, 'What is the positive solution of x² − 9 = 0?', 3, 'Factor as a difference of squares.', '(x − 3)(x + 3) = 0, so the positive solution is 3.'),
      tf('10', 'math', 'quadratic-2', 'Quadratic relationships', 'Interpret the graph of a quadratic function.', '∪', 2, 'True or false: The graph of y = x² opens upward.', true, 'Check whether the x² coefficient is positive.', 'A positive leading coefficient produces a parabola that opens upward.'),
      numeric('10', 'math', 'trig-1', 'Right-triangle trigonometry', 'Apply the Pythagorean theorem and trigonometric foundations.', 'a²+b²', 2, 'A right triangle has legs 6 and 8. What is the hypotenuse?', 10, 'Use a² + b² = c².', '36 + 64 = 100, so c = 10.'),
      mc('10', 'math', 'trig-2', 'Right-triangle trigonometry', 'Choose the correct trigonometric ratio.', 'sin', 3, 'In a right triangle, sin θ equals which ratio?', 'Opposite over hypotenuse', ['Adjacent over hypotenuse', 'Opposite over adjacent'], 'Recall SOH-CAH-TOA.', 'SOH represents sine = opposite ÷ hypotenuse.'),
    ],
    english: [
      mc('10', 'english', 'rhetoric-1', 'Rhetorical analysis', 'Analyze how rhetorical choices affect an audience.', 'ethos', 2, 'A speaker cites years of relevant field experience. Which appeal is emphasized?', 'Ethos', ['Pathos', 'Onomatopoeia'], 'Consider how the detail affects the speaker’s credibility.', 'Ethos is an appeal based on credibility or character.'),
      tf('10', 'english', 'rhetoric-2', 'Rhetorical analysis', 'Recognize how audience shapes communication.', '◎', 2, 'True or false: An effective writer may change examples and tone for different audiences.', true, 'Audience knowledge and expectations affect what will be persuasive.', 'Writers adapt diction, evidence, and tone to suit purpose and audience.'),
      mc('10', 'english', 'comparison-1', 'Comparative analysis', 'Compare how texts develop a shared idea.', '⇄', 3, 'Which comparison is most analytical?', 'Both texts value courage, but one presents it as public action and the other as private endurance.', ['Both texts contain words.', 'The first text is longer.'], 'Look for a meaningful similarity and difference in how an idea develops.', 'The response compares a shared theme and explains a significant difference in treatment.'),
      order('10', 'english', 'comparison-2', 'Comparative analysis', 'Structure a comparative paragraph.', '¶', 2, 'Order a comparative-analysis paragraph.', ['Comparative claim', 'Evidence from text one', 'Evidence from text two', 'Explanation of the relationship'], 'Begin by stating the relationship you will demonstrate.', 'A comparative paragraph makes a claim, presents evidence from both texts, and explains the connection.'),
      mc('10', 'english', 'synthesis-1', 'Research synthesis', 'Synthesize complementary evidence from sources.', 'Σ', 3, 'What does it mean to synthesize sources?', 'Combine related evidence to develop a new understanding', ['Copy sentences from each source', 'Choose the longest source only'], 'Synthesis creates a meaningful relationship among ideas.', 'Synthesis integrates evidence and explains how sources work together or differ.'),
      tf('10', 'english', 'synthesis-2', 'Research synthesis', 'Use citation to distinguish source ideas from original reasoning.', '©', 2, 'True or false: Paraphrased source ideas still require citation.', true, 'Changing the wording does not change where the idea came from.', 'Citation credits the source of an idea whether it is quoted, summarized, or paraphrased.'),
    ],
  },
  '11': {
    science: [
      numeric('11', 'science', 'motion-1', 'Forces and motion', 'Apply Newton’s second law quantitatively.', 'F=ma', 2, 'A 4 kg cart accelerates at 3 m/s². What net force acts on it?', 12, 'Multiply mass by acceleration.', 'F = ma = 4 × 3 = 12 newtons.', ' N'),
      tf('11', 'science', 'motion-2', 'Forces and motion', 'Analyze balanced and unbalanced forces.', 'ΣF', 2, 'True or false: An object moving at constant velocity can have zero net force.', true, 'Constant velocity means acceleration is zero.', 'By Newton’s second law, zero acceleration corresponds to zero net force.'),
      mc('11', 'science', 'energy-1', 'Energy', 'Use conservation of energy in physical systems.', 'E', 2, 'As a falling object speeds up without air resistance, what energy change occurs?', 'Gravitational potential energy becomes kinetic energy', ['Kinetic energy disappears', 'Mass becomes electrical energy'], 'Compare the object’s height and speed.', 'Potential energy decreases while kinetic energy increases; total mechanical energy is conserved.'),
      numeric('11', 'science', 'energy-2', 'Energy', 'Calculate work from force and displacement.', 'W=Fd', 2, 'A 10 N force moves a box 5 m in the force’s direction. How much work is done?', 50, 'Multiply force by displacement.', 'W = Fd = 10 × 5 = 50 joules.', ' J'),
      mc('11', 'science', 'waves-1', 'Waves and electricity', 'Relate wave speed, frequency, and wavelength.', 'v=fλ', 3, 'If wave speed stays constant and frequency doubles, what happens to wavelength?', 'It is halved', ['It doubles', 'It stays unchanged'], 'Rearrange λ = v/f.', 'With constant speed, wavelength is inversely proportional to frequency.'),
      numeric('11', 'science', 'waves-2', 'Waves and electricity', 'Apply Ohm’s law to a circuit.', 'V=IR', 2, 'A 12 V source is connected across a 4 Ω resistor. What current flows?', 3, 'Use I = V/R.', '12 ÷ 4 = 3 amperes.', ' A'),
    ],
    math: [
      numeric('11', 'math', 'exponential-1', 'Exponential functions', 'Evaluate and interpret exponential models.', '2ˣ', 2, 'A culture begins with 5 cells and doubles three times. How many cells result?', 40, 'Multiply by 2 three times.', '5 × 2³ = 40.'),
      tf('11', 'math', 'exponential-2', 'Exponential functions', 'Distinguish exponential and linear change.', 'bˣ', 2, 'True or false: Equal additive changes in x produce equal multiplicative changes in an exponential function.', true, 'Think about repeated multiplication by the base.', 'Exponential functions change by a constant factor over equal input intervals.'),
      mc('11', 'math', 'polynomial-1', 'Polynomial functions', 'Use zeros and factors of polynomials.', '(x−r)', 2, 'If x = 4 is a zero of a polynomial, which expression is a factor?', 'x − 4', ['x + 4', '4x − 1'], 'Use the factor theorem.', 'If f(4) = 0, then x − 4 is a factor.'),
      numeric('11', 'math', 'polynomial-2', 'Polynomial functions', 'Evaluate polynomial expressions.', 'P(2)', 2, 'If P(x) = x³ − 2x + 1, what is P(2)?', 5, 'Substitute 2 for every x.', '2³ − 2(2) + 1 = 8 − 4 + 1 = 5.'),
      mc('11', 'math', 'trig-1', 'Trigonometric functions', 'Connect angles on the unit circle to exact values.', 'π/2', 3, 'What is sin(π/2)?', '1', ['0', '−1'], 'Use the y-coordinate on the unit circle.', 'At π/2, the unit-circle point is (0, 1), so sine is 1.'),
      tf('11', 'math', 'trig-2', 'Trigonometric functions', 'Recognize periodic behavior.', '2π', 3, 'True or false: The sine function has period 2π.', true, 'Ask how far the unit circle travels before repeating.', 'Sine values repeat after one full revolution, or 2π radians.'),
    ],
    english: [
      mc('11', 'english', 'literary-1', 'Literary analysis', 'Analyze how a recurring image develops meaning.', '✦', 3, 'A recurring image that gains symbolic meaning across a work is best described as what?', 'A motif', ['A citation', 'A transition'], 'Look for a repeated element connected to theme.', 'A motif is a recurring image, idea, or element that helps develop a work’s themes.'),
      tf('11', 'english', 'literary-2', 'Literary analysis', 'Distinguish interpretation from plot summary.', '⌕', 2, 'True or false: Literary analysis should explain how textual choices create meaning, not only retell events.', true, 'Analysis answers how and why.', 'Strong analysis makes an interpretive claim and examines evidence and technique.'),
      mc('11', 'english', 'rhetoric-1', 'Argument design', 'Identify concessions and counterarguments.', '↔', 3, 'Why might a writer acknowledge a reasonable opposing view?', 'To build credibility before responding with evidence', ['To avoid making any claim', 'To replace all supporting evidence'], 'Consider how fairness affects an audience’s trust.', 'A thoughtful concession can strengthen ethos and prepare for a focused rebuttal.'),
      order('11', 'english', 'rhetoric-2', 'Argument design', 'Sequence an argument that addresses counterclaims.', '¶', 2, 'Order these parts of a counterclaim section.', ['State the opposing view fairly', 'Acknowledge its reasonable concern', 'Respond with evidence and reasoning', 'Connect back to the main claim'], 'Represent the other view accurately before responding.', 'A fair summary followed by evidence-based response strengthens an argument.'),
      mc('11', 'english', 'sources-1', 'Source synthesis', 'Integrate sources with distinct roles in an argument.', 'Σ', 3, 'Which source combination best supports a complex policy claim?', 'A dataset for scope, expert analysis for causes, and a case study for impact', ['Three sources repeating the same unsupported opinion', 'One source chosen only for its title'], 'Different source types can contribute complementary evidence.', 'Useful synthesis assigns sources distinct, relevant roles within one line of reasoning.'),
      tf('11', 'english', 'sources-2', 'Source synthesis', 'Recognize limits and uncertainty in evidence.', '±', 3, 'True or false: A careful research writer should identify important limitations in the available evidence.', true, 'Responsible claims match the strength of the evidence.', 'Acknowledging limitations improves precision and prevents overclaiming.'),
    ],
  },
  '12': {
    science: [
      mc('12', 'science', 'environment-1', 'Environmental systems', 'Evaluate sustainability trade-offs using evidence.', '♻', 3, 'Which comparison best evaluates two energy systems?', 'Lifecycle emissions, reliability, cost, and ecological effects', ['Color of the equipment', 'Only the initial purchase price'], 'A system has several connected costs and benefits.', 'A lifecycle comparison considers multiple environmental, technical, and economic criteria.'),
      tf('12', 'science', 'environment-2', 'Environmental systems', 'Distinguish correlation from causation in environmental data.', 'r', 3, 'True or false: A correlation between two environmental variables proves that one caused the other.', false, 'Other variables or reverse relationships may exist.', 'Correlation shows association; causal claims require stronger designs and evidence.'),
      numeric('12', 'science', 'gravity-1', 'Astronomy and gravity', 'Apply the inverse-square relationship qualitatively and quantitatively.', '1/r²', 3, 'If distance from a source doubles, to what fraction does an inverse-square effect fall?', 0.25, 'Square the distance change, then take the reciprocal.', '1/(2²) = 1/4 = 0.25.', '', 0.000001),
      mc('12', 'science', 'gravity-2', 'Astronomy and gravity', 'Interpret orbital motion using force and inertia.', 'orbit', 3, 'Why does an orbiting satellite continually fall without striking Earth immediately?', 'Its sideways velocity carries it around Earth as gravity bends its path', ['Gravity stops acting in orbit', 'It has no inertia'], 'Combine forward motion with inward acceleration.', 'Orbital motion results from inertia and continuous gravitational acceleration toward Earth.'),
      mc('12', 'science', 'experiment-1', 'Experimental design', 'Evaluate controls, replication, and measurement quality.', 'n', 3, 'Which change most improves confidence that a treatment caused an observed effect?', 'Random assignment, an appropriate control, and repeated trials', ['Changing several variables together', 'Removing measurement records'], 'Look for a design that limits alternative explanations.', 'Controls, random assignment, and replication strengthen causal inference and reliability.'),
      order('12', 'science', 'experiment-2', 'Experimental design', 'Move from evidence to a qualified scientific conclusion.', '→', 3, 'Order these steps in an evidence-based investigation.', ['Define variables and prediction', 'Collect replicated measurements', 'Analyze uncertainty and patterns', 'State a conclusion with limitations'], 'Planning comes before data collection; qualification follows analysis.', 'Scientific conclusions follow transparent design, data collection, analysis, and evaluation of limits.'),
    ],
    math: [
      numeric('12', 'math', 'functions-1', 'Advanced functions', 'Compose functions and evaluate the result.', 'f∘g', 3, 'If f(x)=2x+1 and g(x)=x², what is f(g(3))?', 19, 'Evaluate g(3) first, then use that output in f.', 'g(3)=9 and f(9)=19.'),
      mc('12', 'math', 'functions-2', 'Advanced functions', 'Choose a model that fits a real pattern.', 'model', 3, 'A quantity grows by 6% each year. Which model type is appropriate?', 'Exponential growth', ['Linear decrease', 'Constant function'], 'A constant percent change means repeated multiplication.', 'Repeated percentage growth is modeled exponentially.'),
      numeric('12', 'math', 'trig-1', 'Trigonometric applications', 'Use periodic models in context.', 'T', 3, 'A wheel completes 5 rotations in 20 seconds. What is its period in seconds per rotation?', 4, 'Divide total time by the number of cycles.', '20 ÷ 5 = 4 seconds per rotation.', ' seconds'),
      mc('12', 'math', 'trig-2', 'Trigonometric applications', 'Interpret amplitude in a sinusoidal model.', 'A', 3, 'A tide varies from 1 m to 5 m. What is the amplitude?', '2 m', ['3 m', '4 m'], 'Amplitude is half the distance between maximum and minimum.', '(5 − 1) ÷ 2 = 2 metres.'),
      numeric('12', 'math', 'statistics-1', 'Statistics and probability', 'Compute an expected value from outcomes.', 'E(X)', 3, 'A game pays 10 points with probability 0.3 and 0 otherwise. What is the expected point value?', 3, 'Multiply each outcome by its probability and add.', '10(0.3) + 0(0.7) = 3 points.', ' points'),
      tf('12', 'math', 'statistics-2', 'Statistics and probability', 'Interpret confidence and sampling variability.', 'CI', 3, 'True or false: A larger well-designed random sample generally reduces sampling variability.', true, 'Think about how much one unusual observation affects a larger sample.', 'Larger random samples generally produce more stable estimates, assuming sound sampling methods.'),
    ],
    english: [
      mc('12', 'english', 'style-1', 'Advanced composition', 'Revise prose for precision and emphasis.', '✎', 3, 'Which revision is most precise?', 'The council postponed the vote until engineers verified the bridge data.', ['The council did a thing later because of some information.', 'The vote was postponed for reasons and things.'], 'Choose concrete actors, actions, and evidence.', 'The precise sentence identifies who acted, what changed, and what evidence was needed.'),
      tf('12', 'english', 'style-2', 'Advanced composition', 'Use syntax deliberately for meaning and rhythm.', ';', 3, 'True or false: Sentence length and structure can be varied deliberately to control pace and emphasis.', true, 'Syntax affects how a reader experiences an idea.', 'Strategic variation in syntax supports clarity, rhythm, tone, and emphasis.'),
      mc('12', 'english', 'comparison-1', 'Comparative rhetoric', 'Compare how authors frame the same issue.', 'frame', 3, 'Two authors use the same data but reach different conclusions. What should analysis examine first?', 'How each author selects, frames, and interprets the evidence', ['Which article has more paragraphs', 'Which author’s name appears first'], 'Focus on reasoning and presentation choices.', 'Framing, assumptions, and reasoning can lead authors to interpret shared evidence differently.'),
      order('12', 'english', 'comparison-2', 'Comparative rhetoric', 'Build a sustained comparative line of reasoning.', '⇄', 3, 'Order the core moves in a comparative analysis.', ['Establish a meaningful basis for comparison', 'Analyze evidence from each text', 'Explain similarities and differences in method', 'Draw a larger conclusion from the comparison'], 'Define the relationship before examining evidence.', 'A strong comparison uses a clear basis, balanced evidence, analysis, and a consequential conclusion.'),
      mc('12', 'english', 'research-1', 'Research evaluation', 'Trace claims to evidence and evaluate methodology.', 'method', 3, 'A study makes a broad claim from a small convenience sample. What is the main concern?', 'The sample may not represent the wider population', ['The title is too short', 'The results include numbers'], 'Ask who was included and who was not.', 'Convenience samples can introduce selection bias and limit generalizability.'),
      tf('12', 'english', 'research-2', 'Research evaluation', 'Calibrate claims to the quality of available evidence.', '≈', 3, 'True or false: Responsible synthesis may conclude that evidence is mixed or insufficient.', true, 'A conclusion should not be stronger than its evidence.', 'Accurate research writing reports uncertainty and disagreement when the evidence warrants it.'),
    ],
  },
};
