import { curriculumMap, gradeContexts, gradeLevels, gradeNumber, legacyBandForGrade } from './grades.ts';
import { gradeExtensions } from './grade-extensions.ts';
import type { LegacyAgeBand } from './grades.ts';
import type { Difficulty, GradedActivity, GradeLevel, MatchingActivity, MultipleChoiceActivity, NumericActivity, OrderingActivity, Subject, TrueFalseActivity } from './types.ts';

type MetaKeys = 'id' | 'grade' | 'subject' | 'topic' | 'skillId' | 'skillDescription' | 'assessmentEligible' | 'prerequisiteSkillIds' | 'token' | 'difficulty';
type Draft = Omit<MultipleChoiceActivity, MetaKeys> | Omit<TrueFalseActivity, MetaKeys> | Omit<OrderingActivity, MetaKeys> | Omit<MatchingActivity, MetaKeys> | Omit<NumericActivity, MetaKeys>;
type Pack = { topic: string; token: string; difficulty: Difficulty; activities: [Draft, Draft, Draft] };
type LegacyActivity = Draft & { id: string; subject: Subject; topic: string; token: string; difficulty: Difficulty };

const mc = (activity: string, prompt: string, answer: string, distractors: [string, string], hint: string, explanation: string): Draft => ({ activityType: 'multiple-choice', activity, prompt, answer, choices: [answer, ...distractors], hint, explanation });
const tf = (activity: string, prompt: string, answer: boolean, hint: string, explanation: string): Draft => ({ activityType: 'true-false', activity, prompt, answer, hint, explanation });
const order = (activity: string, prompt: string, correctOrder: string[], hint: string, explanation: string): Draft => ({ activityType: 'ordering', activity, prompt, items: [...correctOrder], correctOrder, hint, explanation });
const match = (activity: string, prompt: string, pairs: { left: string; right: string }[], hint: string, explanation: string): Draft => ({ activityType: 'matching', activity, prompt, pairs, hint, explanation });
const numeric = (activity: string, prompt: string, answer: number, hint: string, explanation: string, suffix?: string, tolerance?: number): Draft => ({ activityType: 'numeric', activity, prompt, answer, hint, explanation, suffix, tolerance });
const pack = (topic: string, token: string, difficulty: Difficulty, ...activities: [Draft, Draft, Draft]): Pack => ({ topic, token, difficulty, activities });

const packs5to7: Record<Subject, Pack[]> = {
  science: [
    pack('Animals and habitats', '⌂', 1,
      mc('Habitat Picker', 'A beaver needs water and trees. Which home fits best?', 'A riverbank', ['A sandy desert', 'A city rooftop'], 'Look for a place with both water and wood.', 'Beavers build lodges near rivers, ponds, and trees.'),
      tf('Creature Check', 'True or false: A polar bear is suited to a cold Arctic habitat.', true, 'Think about its thick fur and layer of fat.', 'Polar bears have features that help them live in Arctic cold.'),
      match('Habitat Match', 'Match each animal to a home where it can meet its needs.', [{ left: 'Frog', right: 'Pond' }, { left: 'Camel', right: 'Desert' }, { left: 'Squirrel', right: 'Woodland' }], 'Think about water, temperature, and shelter.', 'Animals live in habitats that provide food, water, shelter, and space.')),
    pack('Plants and their parts', '✿', 1,
      mc('Plant Part Picker', 'Which plant part takes in water from the soil?', 'Roots', ['Petals', 'Fruit'], 'Look for the part below the ground.', 'Roots anchor a plant and absorb water and minerals.'),
      order('Growing Sequence', 'Put the early stages of a bean plant in order.', ['Seed', 'Root appears', 'Shoot appears', 'First leaves open'], 'Begin with the stage that can be planted.', 'A seed germinates, grows roots and a shoot, then opens leaves.'),
      match('Plant Job Match', 'Match each plant part to its main job.', [{ left: 'Roots', right: 'Take in water' }, { left: 'Stem', right: 'Hold the plant up' }, { left: 'Leaves', right: 'Use light to make food' }], 'Picture where each part is on a plant.', 'Plant parts have structures that help the plant survive and grow.')),
    pack('Life cycles', '↻', 1,
      mc('Life-Cycle Clue', 'What is a young frog with a tail called?', 'A tadpole', ['A chick', 'A caterpillar'], 'It swims before it grows legs.', 'A frog begins as an egg, becomes a tadpole, and later an adult.'),
      order('Butterfly Builder', 'Put the butterfly life cycle in order.', ['Egg', 'Caterpillar', 'Chrysalis', 'Butterfly'], 'Start with the tiny round stage laid on a leaf.', 'Butterflies develop through egg, larva, pupa, and adult stages.'),
      tf('Growing Things', 'True or false: Every living thing stays exactly the same as it grows.', false, 'Think about how a baby animal changes.', 'Living things change as they grow through their life cycles.')),
    pack('Weather and seasons', '☂', 1,
      mc('Weather Gear', 'Dark clouds are bringing rain. Which item will help keep you dry?', 'A raincoat', ['Sunglasses', 'A paper fan'], 'Choose something that blocks water.', 'A raincoat is made from material that resists water.'),
      match('Season Match', 'Match each season with a common change in many places.', [{ left: 'Spring', right: 'Many plants begin growing' }, { left: 'Summer', right: 'Days are often warm' }, { left: 'Autumn', right: 'Many leaves change and fall' }], 'Think about what you notice outdoors through the year.', 'Seasons bring repeating changes in daylight, temperature, plants, and weather.'),
      tf('Cloud Watch', 'True or false: Weather can change from one day to the next.', true, 'Compare a rainy day with a sunny day.', 'Weather describes current air and sky conditions, which can change often.')),
    pack('Senses and body functions', '◎', 1,
      mc('Sense Detective', 'Which sense helps you notice a bell ringing?', 'Hearing', ['Taste', 'Smell'], 'Think about which body part notices sound.', 'Ears help the brain detect sounds through hearing.'),
      match('Body Job Match', 'Match each body part with a job it does.', [{ left: 'Heart', right: 'Pumps blood' }, { left: 'Lungs', right: 'Help us breathe' }, { left: 'Stomach', right: 'Helps break down food' }], 'Feel your chest as you breathe and move.', 'Body organs work together to keep us alive and active.'),
      tf('Body Check', 'True or false: Your skin helps you feel touch.', true, 'Think about how you notice something warm or rough.', 'Touch receptors in skin send information to the brain.')),
    pack('Materials and water', 'H₂O', 2,
      mc('Material Sorter', 'Which material is usually best for a clear window?', 'Glass', ['Wool', 'Cardboard'], 'Choose a material that lets light pass through.', 'Clear glass is transparent, so light can pass through it.'),
      order('Water Change', 'Put these steps in order to make and then melt an ice cube.', ['Pour liquid water into a tray', 'Cool it until it freezes', 'Take out the solid ice', 'Warm it until it melts'], 'Freezing comes before melting.', 'Cooling water can freeze it; warming ice can melt it.'),
      match('Material Property Match', 'Match each material with a useful property.', [{ left: 'Rubber boot', right: 'Water-resistant' }, { left: 'Metal spoon', right: 'Hard' }, { left: 'Wool scarf', right: 'Soft and warm' }], 'Think about why each object uses that material.', 'Materials are selected because their properties suit an object’s purpose.')),
    pack('Light and sound', '♫', 2,
      mc('Light Finder', 'Which object makes its own light?', 'A lit flashlight', ['A mirror', 'The Moon'], 'Choose an object with a light source inside it.', 'A lit flashlight produces light; mirrors and the Moon reflect light.'),
      tf('Sound Test', 'True or false: A drum makes sound when its surface vibrates.', true, 'Watch what happens when a drum is tapped.', 'Vibrating objects make sound waves.'),
      match('Light and Sound Match', 'Match each action with what it changes.', [{ left: 'Tap a drum harder', right: 'Usually makes a louder sound' }, { left: 'Move a lamp closer', right: 'Usually makes an object look brighter' }, { left: 'Cover your ears', right: 'Makes a sound seem quieter' }], 'Imagine trying each action.', 'Loudness and brightness can change when actions or distances change.')),
    pack('Earth, Moon, Sun, and observation', '☀', 2,
      mc('Sky Watch', 'Which object gives Earth most of its light and warmth?', 'The Sun', ['The Moon', 'A cloud'], 'It is the bright star seen in daytime.', 'The Sun is the star that supplies most of Earth’s light and heat.'),
      order('Simple Investigation', 'Put these investigation steps in a sensible order.', ['Ask a question', 'Make a prediction', 'Try the test', 'Observe what happens'], 'A test begins with something you want to find out.', 'Scientists ask, predict, test, and observe to learn from evidence.'),
      tf('Moon Fact Check', 'True or false: The Moon makes all the light we see shining from it.', false, 'Think about sunlight reaching the Moon.', 'The Moon looks bright because it reflects light from the Sun.')),
  ],
  math: [
    pack('Counting and comparing', '12', 1,
      mc('Number Compare', 'Which number is greater than 12?', '15', ['9', '12'], 'Count forward from 12.', 'Fifteen comes after twelve, so it is greater.'),
      numeric('Counting Chest', 'There are 7 shells and 5 more are added. How many shells are there now?', 12, 'Count on five steps from 7.', '7 + 5 = 12 shells.'),
      order('Number Line', 'Put these numbers from least to greatest.', ['4', '8', '11', '16'], 'Start with the number that comes first when counting.', 'Least to greatest means ordering from the smallest value to the largest.')),
    pack('Addition within 20', '+', 1,
      mc('Glow-Berry Add', 'Six glow-berries join eight more. How many are there altogether?', '14', ['12', '16'], 'Make 10 with 6 and 4, then add the 4 left over.', '6 + 8 = 14.'),
      numeric('Star Pairing', 'Nine stars shine, then 7 more appear. How many stars shine now?', 16, 'Count on seven from 9, or make a ten.', '9 + 7 = 16 stars.'),
      tf('Addition Check', 'True or false: 5 + 8 equals 13.', true, 'Count eight more after five.', '5 + 8 = 13.')),
    pack('Subtraction within 20', '−', 1,
      mc('Gem Take-Away', 'Seventeen gems are in a row. Five roll away. How many remain?', '12', ['11', '13'], 'Count back five from 17.', '17 − 5 = 12.'),
      numeric('Balloon Count', 'There are 14 balloons. Six float away. How many are left?', 8, 'Think: 6 plus what makes 14?', '14 − 6 = 8 balloons.'),
      order('Difference Order', 'Put these subtraction answers from smallest to largest.', ['10 − 8', '9 − 5', '12 − 6'], 'Work out each difference before moving the cards.', 'The answers are 2, 4, and 6.')),
    pack('Patterns and parity', '2,4', 1,
      mc('Pattern Step', 'The path shows 3, 6, 9, 12. What comes next?', '15', ['13', '16'], 'The same amount is added each time.', 'The pattern adds 3, so 12 + 3 = 15.'),
      tf('Even Number Check', 'True or false: 14 is even because it can be shared into two equal whole-number groups.', true, 'Try making two groups of 7.', 'Fourteen is even because 14 = 7 + 7.'),
      match('Odd or Even Match', 'Match each number to the clue that proves whether it is odd or even.', [{ left: '5', right: 'Odd: one remains after pairing' }, { left: '8', right: 'Even: makes two groups of four' }, { left: '11', right: 'Odd: makes five pairs with one left' }], 'Even numbers can be paired with none left over.', 'Five and eleven are odd; eight is even.')),
    pack('2D and 3D shapes', '◇', 1,
      mc('Shape Door', 'Which 2D shape has three straight sides?', 'Triangle', ['Circle', 'Square'], 'Count the sides of each flat shape.', 'Every triangle has three straight sides.'),
      match('Shape Feature Match', 'Match each shape to a feature.', [{ left: 'Circle', right: 'No straight sides' }, { left: 'Cube', right: 'Six square faces' }, { left: 'Cylinder', right: 'Two circular faces' }], 'Picture each shape or trace its faces.', 'Shapes can be identified by sides, corners, faces, and curved surfaces.'),
      tf('Shape Check', 'True or false: A sphere has corners.', false, 'Think about a ball rolling smoothly.', 'A sphere has one curved surface and no corners.')),
    pack('Measurement and time', '⌚', 2,
      mc('Length Choice', 'Which unit is sensible for measuring a pencil?', 'Centimetres', ['Hours', 'Litres'], 'Choose a unit for length, not time or capacity.', 'Centimetres are useful for measuring short lengths.'),
      numeric('Clock Challenge', 'A game begins at 3 o’clock and lasts 2 hours. At what hour does it end?', 5, 'Move the hour hand forward twice.', 'Two hours after 3 o’clock is 5 o’clock.', ' o’clock'),
      order('Length Order', 'Put these objects from usually shortest to usually longest.', ['Button', 'Pencil', 'Bed', 'Bus'], 'Imagine placing them beside one another.', 'A button is usually shortest, followed by a pencil, bed, and bus.')),
    pack('Money and equal sharing', '¢', 2,
      numeric('Coin Total', 'You have one 10-cent coin and two 5-cent coins. How many cents altogether?', 20, 'Add 10 + 5 + 5.', 'The coins total 20 cents.', ' cents'),
      mc('Fair Share', 'Twelve crackers are shared equally by 3 explorers. How many does each explorer receive?', '4', ['3', '9'], 'Make three equal groups.', '12 shared into 3 equal groups gives 4 in each group.'),
      tf('Sharing Check', 'True or false: Sharing 10 berries equally between 2 friends gives 5 berries each.', true, 'Two equal groups of 5 make 10.', '10 ÷ 2 = 5.')),
    pack('Fractions, graphs, and reasoning', '½', 2,
      mc('Half Finder', 'Which picture idea describes one half?', 'One of two equal parts', ['One of three equal parts', 'Two unequal parts'], 'A half needs exactly two equal pieces.', 'One half is one of two equal parts of a whole.'),
      match('Picture Graph Read', 'A picture graph uses one ★ for two books. Match the stars to the number of books.', [{ left: '★', right: '2 books' }, { left: '★★', right: '4 books' }, { left: '★★★', right: '6 books' }], 'Count by twos for each star.', 'When each symbol represents two, multiply the number of symbols by 2.'),
      numeric('Reasoning Box', 'I am greater than 6, less than 10, and odd. I am also one more than 8. What number am I?', 9, 'Find one more than 8, then check every clue.', 'The number is 9: it is odd, greater than 6, and less than 10.')),
  ],
  english: [
    pack('Letter sounds and phonics', 'B', 1,
      mc('Beginning Sound', 'Which word begins with the same sound as boat?', 'Ball', ['Moon', 'Sun'], 'Stretch the first sound: b-b-boat.', 'Boat and ball begin with the /b/ sound.'),
      match('Sound Match', 'Match each first letter to a word that begins with its sound.', [{ left: 'M', right: 'moon' }, { left: 'S', right: 'sun' }, { left: 'F', right: 'fish' }], 'Say each word slowly and listen to the start.', 'Letters can represent the first sounds in spoken words.'),
      tf('Phonics Check', 'True or false: Fish begins with the /f/ sound.', true, 'Say “fish” slowly.', 'The letter F represents the first sound in fish.')),
    pack('Rhyming and word families', '♫', 1,
      mc('Rhyme Catch', 'Which word rhymes with light?', 'Night', ['Leaf', 'Lamp'], 'Listen for the same ending sound.', 'Light and night share the /ight/ ending sound.'),
      match('Rhyme Match', 'Match each word with a rhyming partner.', [{ left: 'cat', right: 'hat' }, { left: 'log', right: 'frog' }, { left: 'cake', right: 'lake' }], 'Say the pairs aloud and listen to their endings.', 'Rhyming words share the same or very similar ending sounds.'),
      tf('Rhyme Check', 'True or false: Star and car rhyme.', true, 'Listen to the sound after the first consonant.', 'Star and car share the /ar/ sound.')),
    pack('Spelling patterns', 'sh', 1,
      mc('Spelling Picker', 'Which word is spelled correctly?', 'ship', ['sip h', 'shep'], 'Listen for /sh/ at the beginning and short /i/.', 'Ship is spelled s-h-i-p.'),
      order('Build a Word', 'Put these letters in order to spell frog.', ['f', 'r', 'o', 'g'], 'Say each sound from beginning to end.', 'The sounds /f/ /r/ /o/ /g/ form frog.'),
      match('Ending Match', 'Match each word beginning to its ending.', [{ left: 'c', right: 'at' }, { left: 's', right: 'un' }, { left: 'p', right: 'ig' }], 'Join the sounds and listen for a real word.', 'The parts make cat, sun, and pig.')),
    pack('Singular and plural', '+s', 1,
      mc('More Than One', 'There is one fox. Now there are two ___.', 'foxes', ['fox', 'foxed'], 'Choose the word that means more than one fox.', 'Foxes is the plural form of fox.'),
      match('One or More Match', 'Match each singular word with its plural.', [{ left: 'cat', right: 'cats' }, { left: 'dish', right: 'dishes' }, { left: 'baby', right: 'babies' }], 'Look at how each ending changes.', 'Plural endings can include -s, -es, or a change from y to ies.'),
      tf('Plural Check', 'True or false: The word dogs means more than one dog.', true, 'Notice the s at the end.', 'Dogs is the plural form of dog.')),
    pack('Nouns, verbs, and adjectives', 'Aa', 1,
      mc('Action Word', 'Which word is the verb in “The rabbit hops quickly”?', 'hops', ['rabbit', 'quickly'], 'Find the word that tells the action.', 'Hops tells what the rabbit does, so it is the verb.'),
      match('Word Job Match', 'Match each word to its job.', [{ left: 'river', right: 'Noun' }, { left: 'jumps', right: 'Verb' }, { left: 'sparkly', right: 'Adjective' }], 'A noun names, a verb acts, and an adjective describes.', 'River names a thing, jumps shows action, and sparkly describes.'),
      tf('Describing Word', 'True or false: Soft is an adjective in “the soft blanket.”', true, 'Ask which word describes the blanket.', 'Soft describes the noun blanket, so it is an adjective.')),
    pack('Capitals and punctuation', '.!?', 1,
      mc('Ending Mark', 'Which mark completes “Where is my map__”', '?', ['.', '!'], 'The sentence asks a question.', 'A question mark ends a direct question.'),
      order('Sentence Builder', 'Put the words in order to make a statement.', ['Mina', 'finds', 'the', 'key.'], 'Begin with the name and finish with the period.', '“Mina finds the key.” is a complete statement.'),
      tf('Capital Check', 'True or false: A sentence should begin with a capital letter.', true, 'Look at the first letter in a book sentence.', 'Standard written sentences begin with a capital letter.')),
    pack('Sequence and comprehension', '1→3', 2,
      order('Story Sequence', 'Put the events in a sensible order.', ['Noor plants a seed.', 'A shoot appears.', 'Leaves open.', 'A flower blooms.'], 'Begin with the action that starts the growth.', 'Planting comes before sprouting, leaves, and flowering.'),
      mc('Detail Detective', 'Read: “Ivo tucked the tiny map into his blue backpack.” Where did Ivo put the map?', 'In his backpack', ['Under a tree', 'On a table'], 'Look for the words after “into his.”', 'The sentence directly says Ivo put the map in his backpack.'),
      tf('Reading Check', 'Read: “The puppy slept beside the warm stove.” True or false: The puppy was beside the stove.', true, 'Find the place word in the sentence.', 'Beside tells where the puppy slept.')),
    pack('Vocabulary in context', '⌕', 2,
      mc('Meaning Clue', '“The kitten was tiny enough to fit in a hat.” What does tiny mean?', 'Very small', ['Very loud', 'Very fast'], 'The hat gives a clue about size.', 'Tiny means very small.'),
      match('Opposite Match', 'Match each word with its opposite.', [{ left: 'hot', right: 'cold' }, { left: 'begin', right: 'end' }, { left: 'full', right: 'empty' }], 'Think of a word with the reverse meaning.', 'The matched words have opposite meanings.'),
      tf('Context Check', '“The path was narrow, so only one person could walk on it.” True or false: Narrow means not wide.', true, 'Use the clue that only one person fits.', 'The context shows that narrow means having little width.')),
  ],
};

const packs8to10: Record<Subject, Pack[]> = {
  science: [
    pack('Ecosystems and food chains', '→', 1,
      mc('Food-Chain Rescue', 'In grass → rabbit → fox, which organism is the producer?', 'Grass', ['Rabbit', 'Fox'], 'A producer makes its own food using sunlight.', 'Grass is a plant, so it produces food through photosynthesis.'),
      order('Energy Path', 'Put this pond food chain in order from energy source to top consumer.', ['Sun', 'Algae', 'Tadpole', 'Heron'], 'Begin with the source of light energy.', 'Energy moves from the Sun to algae, then through consumers.'),
      match('Ecosystem Role Match', 'Match each organism to its ecosystem role.', [{ left: 'Oak tree', right: 'Producer' }, { left: 'Caterpillar', right: 'Consumer' }, { left: 'Fungus', right: 'Decomposer' }], 'Ask how each organism gets energy.', 'Producers make food, consumers eat organisms, and decomposers recycle matter.')),
    pack('Adaptations and life cycles', '↻', 1,
      mc('Adaptation Detective', 'Which feature most helps a duck move through water?', 'Webbed feet', ['Sharp claws for climbing', 'Dry scales'], 'Picture the feet acting like paddles.', 'Webbed feet push against water and help ducks swim.'),
      tf('Life-Cycle Check', 'True or false: Metamorphosis is a major change in body form during a life cycle.', true, 'Think about a caterpillar becoming a butterfly.', 'Metamorphosis describes a major developmental change in form.'),
      match('Young Animal Match', 'Match each adult animal to its young stage.', [{ left: 'Frog', right: 'Tadpole' }, { left: 'Butterfly', right: 'Caterpillar' }, { left: 'Chicken', right: 'Chick' }], 'Recall how each animal begins life after hatching.', 'Different animals have distinct names and forms in young stages.')),
    pack('Matter and state changes', 'H₂O', 1,
      mc('Matter Mixer', 'Ice melts into liquid water. What caused this change?', 'Heat energy entering the ice', ['Gravity disappearing', 'The ice gaining air'], 'Melting happens when a solid gets warmer.', 'Ice absorbs heat and changes from solid water to liquid water.'),
      order('Water State Cycle', 'Order the changes as liquid water is heated, cooled into droplets, and frozen.', ['Liquid water', 'Water vapour', 'Liquid droplets', 'Solid ice'], 'Heating causes evaporation first; later cooling changes the state.', 'Water can evaporate, condense, and freeze as energy changes.'),
      match('State Match', 'Match each example to its state of matter.', [{ left: 'Ice cube', right: 'Solid' }, { left: 'Rain', right: 'Liquid' }, { left: 'Water vapour', right: 'Gas' }], 'Notice whether the material keeps shape, flows, or spreads out.', 'Solids keep shape, liquids flow, and gases spread to fill space.')),
    pack('Forces and motion', 'F', 2,
      mc('Force Finder', 'A rolling ball slows on grass mainly because of which force?', 'Friction', ['Gravity turning off', 'Magnetism'], 'The rough surface rubs against the ball.', 'Friction opposes motion between touching surfaces.'),
      tf('Motion Check', 'True or false: A stronger push can change an object’s speed more than a gentle push.', true, 'Compare softly and strongly pushing the same toy car.', 'Greater force can produce a greater change in motion.'),
      match('Force Effect Match', 'Match each action to its likely effect.', [{ left: 'Push a swing forward', right: 'Changes its motion' }, { left: 'Drop a ball', right: 'Gravity pulls it down' }, { left: 'Rub hands together', right: 'Friction makes heat' }], 'Think about pushes, pulls, gravity, and rubbing.', 'Forces can change motion, and friction can transfer energy as heat.')),
    pack('Heat, light, and sound', '♫', 2,
      mc('Energy Transfer', 'A metal spoon left in hot soup becomes warm. What transferred to the spoon?', 'Thermal energy', ['Moonlight', 'Sound only'], 'Heat moves from warmer matter to cooler matter.', 'Thermal energy transferred from the soup to the spoon by conduction.'),
      order('Shadow Test', 'Order the steps for testing how distance from a lamp changes a shadow.', ['Place an object near the lamp', 'Measure its shadow', 'Move the object farther away', 'Measure and compare again'], 'Keep the object and lamp the same while changing distance.', 'Measuring before and after one change supports a fair comparison.'),
      tf('Sound Evidence', 'True or false: Sound can travel through solids as vibrations.', true, 'Think about hearing a tap through a table.', 'Sound waves can travel through solids, liquids, and gases.')),
    pack('Earth systems and water', '☁', 2,
      mc('Rock Clue', 'Which process breaks rock into smaller pieces without moving it away?', 'Weathering', ['Evaporation', 'Photosynthesis'], 'The word describes wearing rock down in place.', 'Weathering breaks rock down; erosion moves the pieces.'),
      order('Water-Cycle Route', 'Put these water-cycle processes in order, beginning with ocean water warmed by the Sun.', ['Evaporation', 'Condensation', 'Precipitation', 'Collection'], 'Water first rises as vapour and later forms clouds.', 'Water evaporates, condenses, falls, and collects before cycling again.'),
      match('Earth Process Match', 'Match each process to what happens.', [{ left: 'Weathering', right: 'Rock breaks down' }, { left: 'Erosion', right: 'Sediment moves' }, { left: 'Deposition', right: 'Sediment settles' }], 'Follow a grain of sand from rock to a resting place.', 'Weathering, erosion, and deposition reshape Earth’s surface.')),
    pack('Solar system and body systems', '♁', 2,
      mc('Planet Signal', 'Which planet is known for its large, visible ring system?', 'Saturn', ['Mercury', 'Mars'], 'Its rings contain many pieces of ice and rock.', 'Saturn has the solar system’s most prominent ring system.'),
      match('Body System Match', 'Match each body system to its main job.', [{ left: 'Circulatory', right: 'Transports blood' }, { left: 'Respiratory', right: 'Exchanges oxygen and carbon dioxide' }, { left: 'Digestive', right: 'Breaks food into usable nutrients' }], 'Think about the heart, lungs, and stomach.', 'Body systems have specialized jobs and work together.'),
      tf('Orbit Check', 'True or false: Earth completes one orbit around the Sun in about one year.', true, 'An orbit is one trip around another object.', 'Earth’s revolution around the Sun defines a year.')),
    pack('Fair tests and evidence', '⌕', 3,
      mc('Variable Detective', 'To test whether sunlight affects plant growth, what should be changed on purpose?', 'Amount of sunlight', ['Plant type and sunlight together', 'Pot size every day'], 'A fair test changes one main factor.', 'The amount of sunlight is the independent variable in this test.'),
      order('Investigation Builder', 'Put these scientific steps in a useful order.', ['Ask a testable question', 'Plan a fair test', 'Collect observations', 'Compare results and conclude'], 'Planning comes before collecting results.', 'A careful investigation moves from question to evidence-based conclusion.'),
      tf('Evidence Check', 'True or false: Repeating a test can help show whether a result is dependable.', true, 'One result might happen by chance or error.', 'Repeated trials help reveal consistent patterns and reduce random error.')),
  ],
  math: [
    pack('Four operations', '×÷', 1,
      mc('Multiplication Mission', 'Eight hatchlings each need 4 berries. How many berries are needed?', '32', ['24', '36'], 'Multiply the number of groups by the amount in each group.', '8 × 4 = 32 berries.'),
      numeric('Division Dock', 'Forty-two supplies are shared equally among 6 crews. How many supplies does each crew receive?', 7, 'Find the number that makes 6 × something equal 42.', '42 ÷ 6 = 7.'),
      match('Operation Match', 'Match each expression to its value.', [{ left: '36 ÷ 4', right: '9' }, { left: '7 × 6', right: '42' }, { left: '58 − 19', right: '39' }], 'Calculate each expression carefully.', 'The matched equations have equal values.')),
    pack('Multi-step problems', '1→2', 2,
      numeric('Supply Story', 'A cart carries 5 boxes with 8 tools in each. Twelve tools are used. How many tools remain?', 28, 'First multiply, then subtract the tools used.', '5 × 8 = 40, and 40 − 12 = 28.'),
      mc('Journey Planner', 'A team walks 3 km in the morning and twice that distance after lunch. How far altogether?', '9 km', ['6 km', '12 km'], 'Find twice 3, then add the morning distance.', 'The afternoon distance is 6 km; 3 + 6 = 9 km.'),
      order('Problem-Solving Steps', 'Order the steps for solving a two-step word problem.', ['Identify what is asked', 'Choose the first operation', 'Use that result in the second operation', 'Check whether the answer makes sense'], 'Understand the question before calculating.', 'Planning and checking help prevent operation and interpretation errors.')),
    pack('Factors and multiples', '×', 2,
      mc('Factor Gate', 'Which number is a factor of 24?', '6', ['5', '7'], 'A factor divides 24 with no remainder.', '24 ÷ 6 = 4, so 6 is a factor.'),
      match('Multiple Match', 'Match each number to a multiple of it.', [{ left: '4', right: '20' }, { left: '6', right: '42' }, { left: '9', right: '54' }], 'Check whether the right number appears in the left number’s times table.', '20, 42, and 54 are products of the matched factors.'),
      tf('Prime Check', 'True or false: 13 is prime because its only positive factors are 1 and 13.', true, 'Try dividing 13 by 2, 3, or 4.', 'A prime number has exactly two positive factors.')),
    pack('Fractions and decimals', '¾', 2,
      mc('Equivalent Fraction Forge', 'Which fraction is equivalent to 3/4?', '6/8', ['4/7', '9/16'], 'Multiply the numerator and denominator by the same number.', 'Multiplying 3/4 by 2/2 gives 6/8.'),
      numeric('Decimal Supply', 'A crystal weighs 1.4 kg and another weighs 0.7 kg. What is their total weight?', 2.1, 'Line up the decimal points before adding.', '1.4 + 0.7 = 2.1 kilograms.', ' kg', 0.001),
      order('Fraction Line', 'Put these values from least to greatest.', ['0.25', '1/2', '0.75', '1'], 'Rewrite the fractions as decimals or picture quarters.', 'The values are one quarter, one half, three quarters, and one whole.')),
    pack('Measurement and conversion', 'cm', 2,
      numeric('Length Converter', 'A ribbon is 3 metres long. How many centimetres is that?', 300, 'Each metre contains 100 centimetres.', '3 × 100 = 300 centimetres.', ' cm'),
      mc('Capacity Choice', 'Which unit is most sensible for the water in a large bottle?', 'Litres', ['Kilometres', 'Degrees'], 'Choose a unit for liquid capacity.', 'Litres measure capacity or liquid volume.'),
      match('Unit Match', 'Match each quantity to a sensible unit.', [{ left: 'Mass of an apple', right: 'Grams' }, { left: 'Length of a room', right: 'Metres' }, { left: 'Time for a lesson', right: 'Minutes' }], 'Decide whether each quantity is mass, length, or time.', 'Appropriate units make measurements meaningful and easy to compare.')),
    pack('Geometry, area, and perimeter', '∠', 2,
      numeric('Perimeter Patrol', 'A rectangle is 8 m long and 3 m wide. What is its perimeter?', 22, 'Add all four sides, or use 2 × (length + width).', '2 × (8 + 3) = 22 metres.', ' m'),
      mc('Angle Finder', 'Which description fits an acute angle?', 'Less than 90°', ['Exactly 90°', 'Greater than 180°'], 'Compare it with the square corner of a right angle.', 'An acute angle measures more than 0° and less than 90°.'),
      match('Geometry Match', 'Match each figure to the correct property.', [{ left: 'Square', right: 'Four equal sides' }, { left: 'Rectangle', right: 'Four right angles' }, { left: 'Equilateral triangle', right: 'Three equal sides' }], 'Use side lengths and angle features.', 'Geometric properties define and classify shapes.')),
    pack('Patterns and data', '▥', 2,
      mc('Sequence Signal', 'The sequence is 5, 9, 13, 17. What comes next?', '21', ['20', '22'], 'Find the amount added each time.', 'The rule adds 4, so 17 + 4 = 21.'),
      numeric('Graph Reader', 'A bar graph shows 12 red votes, 9 blue votes, and 7 green votes. How many more red than green votes?', 5, 'Compare the red and green bars by subtraction.', '12 − 7 = 5 more votes.'),
      order('Data Order', 'Order these data values from least to greatest.', ['6', '11', '14', '19'], 'Compare the tens digits, then ones digits.', 'The ordered values increase from 6 to 19.')),
    pack('Probability and reasoning', 'P', 3,
      mc('Chance Chamber', 'A bag has 3 red and 7 blue gems. What is the probability of choosing red?', '3/10', ['7/10', '1/3'], 'Count red outcomes over all outcomes.', 'There are 3 favourable outcomes among 10 total, so the probability is 3/10.'),
      tf('Probability Check', 'True or false: Rolling a standard six-sided die has a 1/6 chance of showing 4.', true, 'Only one face shows 4 among six equally likely faces.', 'One favourable face out of six gives probability 1/6.'),
      match('Likelihood Match', 'Match each event to its likelihood.', [{ left: 'Sun rises tomorrow', right: 'Certain or nearly certain' }, { left: 'Roll a 7 on a standard die', right: 'Impossible' }, { left: 'Flip heads on a fair coin', right: 'Even chance' }], 'Think about which outcomes can happen and how many are equally likely.', 'Events range from impossible to certain, with fair-coin heads having probability 1/2.')),
  ],
  english: [
    pack('Parts of speech', 'Aa', 1,
      mc('Verb Vine', 'Which word is the verb in “The silver bird sings softly”?', 'sings', ['silver', 'softly'], 'A verb tells an action or state.', 'Sings tells what the bird does.'),
      match('Word-Class Match', 'Match each word to its part of speech.', [{ left: 'mountain', right: 'Noun' }, { left: 'whispers', right: 'Verb' }, { left: 'careful', right: 'Adjective' }], 'Ask whether the word names, acts, or describes.', 'Mountain names, whispers acts, and careful describes.'),
      tf('Adverb Check', 'True or false: Quietly is an adverb in “Mara quietly closed the door.”', true, 'The word tells how Mara closed it.', 'Quietly modifies the verb closed.')),
    pack('Agreement and editing', '✓', 1,
      mc('Agreement Repair', 'Which sentence has correct subject-verb agreement?', 'The lanterns glow brightly.', ['The lanterns glows brightly.', 'The lantern glow brightly.'], 'A plural subject needs the matching verb form.', 'Lanterns is plural, so glow is the correct present-tense verb.'),
      order('Sentence Repair', 'Order the words to make a correct sentence.', ['The', 'three explorers', 'carry', 'their maps.'], 'Place the subject before the verb.', '“The three explorers carry their maps.” has clear order and agreement.'),
      tf('Editing Check', 'True or false: “My friend walk to school” has correct agreement.', false, 'A singular subject usually needs walks in the present tense.', 'The correct sentence is “My friend walks to school.”')),
    pack('Prefixes, suffixes, and roots', 're-', 1,
      mc('Prefix Portal', 'What does re- mean in rebuild?', 'Again', ['Before', 'Not'], 'To replay is to play one more time.', 'The prefix re- often means again.'),
      match('Affix Match', 'Match each word part to its usual meaning.', [{ left: 'un-', right: 'Not' }, { left: 'pre-', right: 'Before' }, { left: '-less', right: 'Without' }], 'Think of unhappy, preview, and fearless.', 'Prefixes and suffixes add meaning to base words.'),
      tf('Word-Part Check', 'True or false: Careless means “without care.”', true, 'Focus on the suffix -less.', 'The suffix -less means without.')),
    pack('Synonyms and antonyms', '≈', 1,
      mc('Synonym Search', 'Choose a synonym for enormous.', 'Huge', ['Tiny', 'Quiet'], 'A synonym has a similar meaning.', 'Huge and enormous both mean very large.'),
      match('Opposite Match', 'Match each word to its antonym.', [{ left: 'ancient', right: 'modern' }, { left: 'expand', right: 'shrink' }, { left: 'generous', right: 'selfish' }], 'Look for meanings that contrast.', 'Antonyms have opposite or strongly contrasting meanings.'),
      tf('Meaning Check', 'True or false: Rapid and quick are synonyms.', true, 'Both words describe speed.', 'Rapid and quick have similar meanings.')),
    pack('Context clues and figurative language', '⌕', 2,
      mc('Context Clue Hunt', '“The path was slick, so Jo walked carefully.” What does slick mean?', 'Slippery', ['Bright', 'Narrow'], 'Use the reason Jo walked carefully.', 'The context shows that slick means slippery.'),
      match('Figurative Match', 'Match each expression to its likely meaning.', [{ left: 'Busy as a bee', right: 'Very active' }, { left: 'A heart of gold', right: 'Very kind' }, { left: 'Light as a feather', right: 'Very light' }], 'Do not take each expression literally.', 'Figurative comparisons communicate qualities through images.'),
      tf('Simile Check', 'True or false: “The lake was like glass” is a simile.', true, 'Look for the comparison word like.', 'A simile compares using like or as.')),
    pack('Main idea and details', '◎', 2,
      mc('Main-Idea Mission', 'Read: “Bees visit flowers for nectar. As they move, pollen sticks to them and reaches other flowers. This helps many plants make seeds.” What is the main idea?', 'Bees help pollinate plants', ['All flowers are yellow', 'Bees build nests in trees'], 'Choose the idea supported by every sentence.', 'The details explain how bees move pollen and help plants reproduce.'),
      order('Summary Builder', 'Order these summary steps.', ['Name the topic', 'Find the most important point', 'Choose supporting details', 'State the idea in your own words'], 'A summary begins by understanding the topic and central point.', 'Strong summaries focus on the central idea and essential details.'),
      tf('Detail Check', 'Read: “Miko filled a bottle, packed a hat, and checked the trail map.” True or false: Miko is preparing for an outing.', true, 'Combine the three actions into one likely purpose.', 'The supplies and map support the inference that Miko is preparing to go out.')),
    pack('Inference, prediction, and sequence', '→', 2,
      mc('Prediction Path', '“Lena packed boots and a raincoat. Dark clouds filled the sky.” What will probably happen?', 'It will rain', ['It will snow indoors', 'The Sun will vanish'], 'Use the clothing and cloud clues.', 'The details support the prediction that rain is coming.'),
      order('Story Sequence', 'Order the events logically.', ['Ari notices a loose bicycle chain.', 'Ari gets the repair tools.', 'Ari tightens the chain.', 'Ari tests the bicycle safely.'], 'Notice, prepare, fix, then test.', 'The sequence follows a sensible problem-and-solution process.'),
      tf('Inference Check', '“Nia yawned and turned off her lamp.” True or false: Nia is probably getting ready to sleep.', true, 'Use both the yawn and the lamp.', 'Those details support the inference that bedtime is near.')),
    pack('Point of view and conventions', '“ ”', 3,
      mc('Point-of-View Finder', 'Which sentence uses first-person point of view?', 'I carried the compass home.', ['She carried the compass home.', 'They carried the compass home.'], 'First person uses I or we.', 'The pronoun I signals first-person narration.'),
      match('Punctuation Match', 'Match each sentence purpose to its ending mark.', [{ left: 'Ask a question', right: '?' }, { left: 'Make a statement', right: '.' }, { left: 'Show strong feeling', right: '!' }], 'Think about how each sentence sounds.', 'Ending punctuation signals sentence purpose and tone.'),
      order('Dialogue Builder', 'Order the parts to make a correctly punctuated line of dialogue.', ['“Wait', 'for', 'me!”', 'called Ren.'], 'The spoken words stay inside quotation marks.', 'The completed dialogue is “Wait for me!” called Ren.')),
  ],
};

const packs11to13: Record<Subject, Pack[]> = {
  science: [
    pack('Cells and body systems', 'DNA', 1,
      mc('Cell Scanner', 'Which structure contains most of a eukaryotic cell’s DNA?', 'Nucleus', ['Cell membrane', 'Cytoplasm'], 'It acts as the cell’s main information centre.', 'Most DNA in a eukaryotic cell is stored in the nucleus.'),
      match('Organelle Match', 'Match each cell structure to a main function.', [{ left: 'Cell membrane', right: 'Controls movement into and out of the cell' }, { left: 'Mitochondrion', right: 'Releases usable energy from food' }, { left: 'Ribosome', right: 'Builds proteins' }], 'Connect each structure with the process it supports.', 'Cell structures perform specialized functions that keep cells operating.'),
      tf('System Check', 'True or false: The respiratory and circulatory systems work together to deliver oxygen to body cells.', true, 'Think about lungs, blood, and the heart.', 'The respiratory system exchanges gases, while blood transports oxygen.')),
    pack('Ecosystems and environmental change', '♻', 1,
      mc('Ecosystem Balance', 'If a top predator disappears, what is a likely immediate effect on its prey population?', 'The prey may increase', ['The prey must disappear instantly', 'Sunlight stops reaching producers'], 'Consider what happens when fewer animals hunt the prey.', 'With reduced predation, a prey population may initially grow.'),
      order('Ecological Recovery', 'Order these events after plants begin returning to bare ground.', ['Pioneer plants establish', 'Soil organic matter increases', 'More plant species grow', 'Animal diversity increases'], 'Begin with hardy organisms that can colonize first.', 'Succession gradually changes habitat conditions and community diversity.'),
      match('Change and Effect Match', 'Match each environmental change to a likely effect.', [{ left: 'Habitat fragmentation', right: 'Populations become separated' }, { left: 'Excess fertilizer runoff', right: 'Algal growth may increase' }, { left: 'Planting native species', right: 'Local food webs may gain support' }], 'Trace how each change affects resources or movement.', 'Environmental changes can alter population connections, water quality, and food webs.')),
    pack('Genetics and heredity', 'Aa', 1,
      mc('Heredity Clue', 'What is a gene?', 'A section of DNA that can influence a trait', ['A complete ecosystem', 'A type of body tissue only'], 'Genes are carried in DNA.', 'A gene is a DNA sequence that contributes to a functional product and can influence traits.'),
      tf('Variation Check', 'True or false: Offspring can inherit traits from both biological parents.', true, 'Think about receiving genetic information from egg and sperm cells.', 'Sexual reproduction combines genetic information from two parents.'),
      match('Genetics Match', 'Match each term to its description.', [{ left: 'DNA', right: 'Molecule carrying genetic information' }, { left: 'Gene', right: 'A functional section of DNA' }, { left: 'Trait', right: 'An observable characteristic' }], 'Move from information molecule to section to outcome.', 'DNA contains genes, and gene-environment interactions contribute to traits.')),
    pack('Atoms, elements, and changes', 'p⁺', 2,
      mc('Particle Detector', 'Which subatomic particle has a positive charge?', 'Proton', ['Electron', 'Neutron'], 'Electrons are negative and neutrons are neutral.', 'Protons have positive charge.'),
      match('Matter Match', 'Match each term to the best example.', [{ left: 'Element', right: 'Pure copper' }, { left: 'Compound', right: 'Pure water' }, { left: 'Mixture', right: 'Air' }], 'An element has one kind of atom; a compound has bonded elements.', 'Copper is an element, water a compound, and air a mixture of gases.'),
      tf('Chemical Change Check', 'True or false: Formation of a new substance is evidence of a chemical change.', true, 'A physical change keeps the same substances.', 'Chemical changes rearrange atoms into one or more new substances.')),
    pack('Forces, motion, and energy', 'F=ma', 2,
      mc('Motion Lab', 'For the same mass, what happens to acceleration when the net force increases?', 'Acceleration increases', ['Acceleration becomes zero', 'Mass disappears'], 'Use the relationship between net force, mass, and acceleration.', 'From F = ma, greater net force on the same mass produces greater acceleration.'),
      numeric('Speed Signal', 'A rover travels 180 metres in 12 seconds. What is its average speed?', 15, 'Divide distance by time.', '180 ÷ 12 = 15 metres per second.', ' m/s', 0.001),
      match('Energy Transfer Match', 'Match each device to its main energy change.', [{ left: 'Solar panel', right: 'Light to electrical' }, { left: 'Speaker', right: 'Electrical to sound' }, { left: 'Toaster', right: 'Electrical to thermal' }], 'Identify the input and useful output of each device.', 'Devices transfer or transform energy between forms.')),
    pack('Electricity and circuits', '⚡', 2,
      mc('Circuit Repair', 'What must a simple circuit have for current to flow continuously?', 'A closed conducting path', ['A gap in every wire', 'Only an unconnected battery'], 'Charges need an unbroken route.', 'A closed circuit provides a continuous conducting path.'),
      match('Circuit Part Match', 'Match each component to its role.', [{ left: 'Cell', right: 'Provides potential difference' }, { left: 'Switch', right: 'Opens or closes the path' }, { left: 'Resistor', right: 'Limits current' }], 'Think about power, control, and resistance.', 'Circuit components have distinct roles in controlling energy and current.'),
      tf('Series Circuit Check', 'True or false: Opening one switch in a simple series circuit stops current everywhere in that loop.', true, 'A series circuit has one continuous path.', 'Breaking the only path stops current through the entire series loop.')),
    pack('Earth systems and climate', 'CO₂', 2,
      mc('Climate Evidence', 'Which measurement best describes climate rather than daily weather?', 'Average rainfall over 30 years', ['Temperature at noon today', 'Wind speed during one storm'], 'Climate uses long-term patterns.', 'Long-term averages and ranges describe climate; short events describe weather.'),
      order('Water-Cycle Energy', 'Order these events beginning with solar heating of ocean water.', ['Evaporation', 'Cooling and condensation', 'Precipitation', 'Runoff returning water toward the ocean'], 'Follow water up, into clouds, down, and across land.', 'Solar energy and gravity drive major movements in the water cycle.'),
      tf('Greenhouse Effect Check', 'True or false: Greenhouse gases can absorb and re-emit infrared energy in the atmosphere.', true, 'Think about how the atmosphere slows some outgoing heat transfer.', 'Greenhouse gases interact with infrared radiation and warm the lower atmosphere.')),
    pack('Space, gravity, and scientific reasoning', 'G', 3,
      mc('Orbit Reasoning', 'Why does an orbiting satellite keep falling around Earth instead of moving away in a straight line?', 'Gravity continually changes its direction', ['There is no motion in orbit', 'Air pushes it around Earth'], 'Combine forward motion with an inward force.', 'Gravity provides centripetal acceleration that bends the satellite’s path.'),
      order('Controlled Investigation', 'Order the core parts of a controlled investigation.', ['State a testable question', 'Identify variables and controls', 'Collect repeated measurements', 'Analyze evidence and revise the explanation'], 'Design comes before data, and analysis follows data.', 'Controlled investigations connect a clear question to repeatable evidence.'),
      match('Variable Match', 'Match each variable type to its role.', [{ left: 'Independent variable', right: 'Changed deliberately' }, { left: 'Dependent variable', right: 'Measured as an outcome' }, { left: 'Controlled variable', right: 'Kept the same' }], 'Use changed, measured, and held constant.', 'Clear variable roles make cause-and-effect tests easier to interpret.')),
  ],
  math: [
    pack('Integers and rational numbers', '−3', 1,
      mc('Integer Trail', 'Which value is farthest left on a number line?', '−8', ['−2', '3'], 'Values become smaller as you move left.', 'Negative eight is less than negative two and positive three.'),
      numeric('Temperature Change', 'The temperature rises from −6°C to 5°C. How many degrees does it rise?', 11, 'Find the distance from −6 to 0, then from 0 to 5.', 'The total rise is 6 + 5 = 11 degrees.', '°C'),
      order('Rational Number Line', 'Order these numbers from least to greatest.', ['−1.5', '−1/2', '0.25', '3/4'], 'Rewrite fractions and decimals in one form.', 'The values increase from −1.5 to −0.5 to 0.25 to 0.75.')),
    pack('Fractions, decimals, and percentages', '%', 1,
      mc('Percent Portal', 'Which value is equivalent to 35%?', '0.35', ['3.5', '0.035'], 'Percent means out of 100.', '35% = 35/100 = 0.35.'),
      numeric('Discount Mission', 'A 60-credit tool is discounted by 25%. How many credits is the discount?', 15, 'One quarter is 25%; find one quarter of 60.', '60 × 0.25 = 15 credits.', ' credits'),
      match('Equivalent Value Match', 'Match each fraction to an equivalent value.', [{ left: '1/4', right: '0.25' }, { left: '3/5', right: '60%' }, { left: '7/10', right: '0.7' }], 'Convert each fraction by dividing or using tenths and hundredths.', 'Fractions, decimals, and percentages can represent the same rational number.')),
    pack('Ratios and proportional relationships', '2:5', 1,
      numeric('Ratio Reactor', 'Blue and gold crystals are in a 2:5 ratio. If there are 10 blue crystals, how many are gold?', 25, 'The blue amount was multiplied by 5.', 'Multiplying both parts of 2:5 by 5 gives 10:25.'),
      mc('Proportion Check', 'Which ratio is equivalent to 3:4?', '12:16', ['9:16', '12:20'], 'Multiply both parts by the same factor.', 'Multiplying 3:4 by 4 gives 12:16.'),
      match('Rate Match', 'Match each situation to its unit rate.', [{ left: '180 km in 3 h', right: '60 km/h' }, { left: '$12 for 4 notebooks', right: '$3 each' }, { left: '24 pages in 6 min', right: '4 pages/min' }], 'Divide each total by the number of units.', 'A unit rate compares a quantity with one unit of another quantity.')),
    pack('Expressions and equations', 'x', 2,
      numeric('Equation Gate', 'Solve 3x + 4 = 25. What is x?', 7, 'Undo 4 first, then divide by 3.', '3x = 21, so x = 7.'),
      mc('Expression Match', 'Which expression means “five less than twice n”?', '2n − 5', ['5 − 2n', '2(n − 5)'], 'Start with twice n, then subtract five.', 'Twice n is 2n; five less gives 2n − 5.'),
      order('Equation Steps', 'Order the steps to solve 4x − 9 = 19.', ['Add 9 to both sides', 'Simplify to 4x = 28', 'Divide both sides by 4', 'Conclude x = 7'], 'Undo subtraction before multiplication.', 'Inverse operations isolate x while keeping the equation balanced.')),
    pack('Inequalities and coordinate geometry', '(x,y)', 2,
      mc('Inequality Signal', 'Which value satisfies x + 3 > 8?', '6', ['5', '4'], 'Subtract 3 from both sides, then test the choices.', 'The inequality is x > 5, so 6 works.'),
      match('Quadrant Match', 'Match each point to its quadrant.', [{ left: '(3, 4)', right: 'Quadrant I' }, { left: '(−2, 5)', right: 'Quadrant II' }, { left: '(−4, −1)', right: 'Quadrant III' }], 'Use the signs of x and y.', 'Quadrants are identified by the sign pair of the coordinates.'),
      tf('Coordinate Check', 'True or false: The point (0, 6) lies on the y-axis.', true, 'Points on the y-axis have x-coordinate zero.', 'Because x = 0, the point lies on the y-axis.')),
    pack('Geometry, area, and volume', 'V', 2,
      numeric('Volume Vault', 'A rectangular prism measures 6 cm by 4 cm by 3 cm. What is its volume?', 72, 'Multiply length × width × height.', '6 × 4 × 3 = 72 cubic centimetres.', ' cm³'),
      mc('Angle Equation', 'Two supplementary angles add to 180°. One is 68°. What is the other?', '112°', ['22°', '248°'], 'Subtract the known angle from 180°.', '180° − 68° = 112°.'),
      match('Formula Match', 'Match each figure to an appropriate measure formula.', [{ left: 'Rectangle area', right: 'length × width' }, { left: 'Triangle area', right: '½ × base × height' }, { left: 'Rectangular prism volume', right: 'length × width × height' }], 'Decide whether the measure covers a surface or fills a solid.', 'Area uses square units; volume uses cubic units.')),
    pack('Patterns and algebraic reasoning', 'n', 2,
      mc('Sequence Rule', 'The sequence 7, 12, 17, 22 follows which rule?', 'Add 5', ['Multiply by 5', 'Add 7'], 'Compare consecutive terms.', 'Each term is 5 greater than the previous term.'),
      numeric('Pattern Predictor', 'The rule is 4n + 1. What is the value when n = 6?', 25, 'Substitute 6 for n, then multiply before adding.', '4(6) + 1 = 25.'),
      order('Expression Builder', 'Order the steps to evaluate 3(8 − 2) + 5.', ['Calculate 8 − 2', 'Multiply 3 × 6', 'Add 5', 'Get 23'], 'Follow the order of operations.', 'Parentheses come first, then multiplication, then addition.')),
    pack('Statistics and probability', 'x̄', 3,
      numeric('Mean Machine', 'The scores are 6, 8, 9, and 13. What is the mean?', 9, 'Add the values and divide by how many there are.', 'The sum is 36; 36 ÷ 4 = 9.'),
      mc('Data Display Choice', 'Which display is especially useful for showing change over time?', 'Line graph', ['Unordered list', 'Single tally mark'], 'Think of points connected across time.', 'A line graph clearly displays trends across ordered time intervals.'),
      match('Probability Match', 'Match each event to its probability.', [{ left: 'Roll an even number on a fair die', right: '1/2' }, { left: 'Draw the only red card from 5 cards', right: '1/5' }, { left: 'Roll a 7 on a standard die', right: '0' }], 'Count favourable outcomes over total equally likely outcomes.', 'The probabilities are 3/6, 1/5, and 0.')),
  ],
  english: [
    pack('Sentence structure and clauses', 'S+V', 1,
      mc('Clause Builder', 'Which group of words is an independent clause?', 'The explorers reached camp.', ['Because the storm ended', 'While crossing the bridge'], 'It must express a complete thought on its own.', 'The sentence has a subject, verb, and complete meaning.'),
      match('Clause Match', 'Match each clause to the clue that identifies its type.', [{ left: 'Mira opened the gate.', right: 'Independent: complete thought' }, { left: 'because the key fit', right: 'Dependent: gives a reason' }, { left: 'when daylight returned', right: 'Dependent: gives a time' }], 'Ask whether the words can stand alone as a sentence.', 'Independent clauses stand alone; dependent clauses need another clause.'),
      order('Complex Sentence Builder', 'Order the parts to make a clear complex sentence.', ['Although the trail was steep,', 'the team', 'continued', 'at a steady pace.'], 'Begin with the dependent clause and comma.', 'The dependent clause is followed by an independent clause.')),
    pack('Voice, grammar, and punctuation', ';', 1,
      mc('Active Voice Finder', 'Which sentence uses active voice?', 'Nia solved the riddle.', ['The riddle was solved by Nia.', 'The riddle had been solved.'], 'In active voice, the subject performs the action.', 'Nia is the subject and performs solved.'),
      tf('Semicolon Check', 'True or false: A semicolon can join two closely related independent clauses.', true, 'Each side should be able to stand as a sentence.', 'A semicolon can connect closely related complete clauses.'),
      order('Punctuation Repair', 'Order the parts to create a sentence with introductory punctuation.', ['After the rain stopped,', 'the hikers', 'crossed', 'the bridge.'], 'Use a comma after the introductory dependent clause.', 'The comma separates the introductory clause from the main clause.')),
    pack('Word roots and context', 'bio', 1,
      mc('Root Detective', 'The root bio means life. What does biography most nearly mean?', 'Writing about a person’s life', ['A map of mountains', 'A study of numbers'], 'Combine bio with the idea of written description.', 'Biography is an account of a person’s life.'),
      match('Root Match', 'Match each root to its meaning.', [{ left: 'tele', right: 'far' }, { left: 'aqua', right: 'water' }, { left: 'spect', right: 'look or see' }], 'Think of telephone, aquarium, and spectator.', 'Greek and Latin roots help readers infer unfamiliar words.'),
      tf('Context Check', '“The glass was fragile, so Ren wrapped it carefully.” True or false: Fragile means easily broken.', true, 'Use the careful wrapping as evidence.', 'The context supports the meaning easily broken.')),
    pack('Main idea and textual evidence', '⌕', 2,
      mc('Evidence Finder', 'Passage: “City trees shade sidewalks, absorb some rainwater, and provide habitat for birds. Communities often plant them to improve busy streets.” Which idea is central?', 'City trees provide several community benefits', ['All birds live in cities', 'Rain falls only on streets'], 'Choose the claim supported by all three examples.', 'The details show multiple environmental and community benefits.'),
      order('Evidence Reasoning', 'Order the steps for supporting an inference.', ['State the inference', 'Locate a relevant text detail', 'Explain how the detail supports the inference', 'Check for conflicting evidence'], 'A claim needs evidence and reasoning.', 'Strong analysis connects a reasonable inference to relevant evidence.'),
      tf('Evidence Check', 'True or false: A quotation supports a claim only when it is relevant to that claim.', true, 'Evidence must connect logically to the point.', 'Relevant evidence directly helps establish the claim.')),
    pack('Inference and point of view', 'I', 2,
      mc('Inference Trail', '“Kai checked the clock twice and drummed his fingers.” What can you reasonably infer?', 'Kai is impatient', ['Kai is asleep', 'Kai cannot see the clock'], 'Use the repeated checking and restless movement.', 'Those details suggest Kai is waiting impatiently.'),
      match('Point-of-View Match', 'Match each pronoun pattern to its point of view.', [{ left: 'I, me, we', right: 'First person' }, { left: 'you', right: 'Second person' }, { left: 'he, she, they', right: 'Third person' }], 'Notice who is telling or being addressed.', 'Pronouns are strong signals of narrative point of view.'),
      tf('Perspective Check', 'True or false: A first-person narrator may know less than an all-knowing third-person narrator.', true, 'A character can report only what that character knows.', 'First-person narration is limited to that narrator’s experiences and knowledge.')),
    pack('Author purpose and text structure', '¶', 2,
      mc('Purpose Detector', 'A guide explains steps for safely observing a solar eclipse. What is its main purpose?', 'To instruct', ['To entertain with a fantasy', 'To persuade readers to buy something'], 'Look for step-by-step directions.', 'Procedural directions are written mainly to instruct.'),
      match('Structure Match', 'Match each text signal to its likely structure.', [{ left: 'because, therefore', right: 'Cause and effect' }, { left: 'both, however', right: 'Compare and contrast' }, { left: 'first, next, finally', right: 'Sequence' }], 'Signal words reveal how ideas are organized.', 'Authors use recognizable signals to structure relationships among ideas.'),
      order('Process Structure', 'Order these signal words for a sequence paragraph.', ['First', 'Next', 'Then', 'Finally'], 'Follow the progression from beginning to end.', 'Sequence transitions guide readers through ordered steps.')),
    pack('Figurative language and comparison', '≈', 2,
      mc('Figurative Forge', 'Which sentence uses personification?', 'The wind whispered through the pines.', ['The wind was cold.', 'The wind moved at 20 km/h.'], 'Personification gives a nonhuman thing a human action.', 'Whispered gives the wind a human action.'),
      match('Figure Match', 'Match each example to its device.', [{ left: 'The moon was a silver coin.', right: 'Metaphor' }, { left: 'Bright as a beacon', right: 'Simile' }, { left: 'The alarm screamed.', right: 'Personification' }], 'Look for direct comparison, like/as, or human qualities.', 'Metaphor, simile, and personification create meaning in different ways.'),
      tf('Metaphor Check', 'True or false: “The classroom was a beehive” is a metaphor for busy activity.', true, 'The sentence compares directly without like or as.', 'The metaphor suggests a place full of movement and activity.')),
    pack('Revision and comparing ideas', '✎', 3,
      mc('Revision Workshop', 'Which revision is most concise?', 'The rain ended, and the match resumed.', ['Due to the fact that the rain ended, the match resumed again.', 'The rain, which was rain, ended and then the match resumed back.'], 'Remove repeated or unnecessary words.', 'The concise version communicates the same meaning clearly.'),
      order('Paragraph Builder', 'Order these parts of an explanatory paragraph.', ['Topic sentence', 'Relevant evidence', 'Explanation of the evidence', 'Concluding sentence'], 'Begin with the main point and end by wrapping it up.', 'A clear paragraph introduces, supports, explains, and concludes an idea.'),
      match('Comparison Match', 'Match each linking phrase to its purpose.', [{ left: 'Similarly', right: 'Show a likeness' }, { left: 'In contrast', right: 'Show a difference' }, { left: 'For example', right: 'Introduce evidence or illustration' }], 'Consider the relationship each phrase signals.', 'Transitions make comparisons and evidence relationships clear.')),
  ],
};

const ageCode: Record<LegacyAgeBand, string> = { '5–7': '5-7', '8–10': '8-10', '11–13': '11-13' };
const slug = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

const buildSubjectBank = (age: LegacyAgeBand, subject: Subject, packs: Pack[]): LegacyActivity[] => packs.flatMap((item) => item.activities.map((draft, index) => ({
  ...draft,
  id: `${ageCode[age]}-${subject}-${slug(item.topic)}-${index + 1}`,
  subject,
  topic: item.topic,
  token: item.token,
  difficulty: item.difficulty,
} as LegacyActivity)));

const legacyQuestionBank: Record<LegacyAgeBand, Record<Subject, LegacyActivity[]>> = {
  '5–7': {
    science: buildSubjectBank('5–7', 'science', packs5to7.science),
    math: buildSubjectBank('5–7', 'math', packs5to7.math),
    english: buildSubjectBank('5–7', 'english', packs5to7.english),
  },
  '8–10': {
    science: buildSubjectBank('8–10', 'science', packs8to10.science),
    math: buildSubjectBank('8–10', 'math', packs8to10.math),
    english: buildSubjectBank('8–10', 'english', packs8to10.english),
  },
  '11–13': {
    science: buildSubjectBank('11–13', 'science', packs11to13.science),
    math: buildSubjectBank('11–13', 'math', packs11to13.math),
    english: buildSubjectBank('11–13', 'english', packs11to13.english),
  },
};

const lowerFirst = (value: string) => `${value.charAt(0).toLowerCase()}${value.slice(1)}`;
const gradeActivity = (grade: GradeLevel, subject: Subject, activity: LegacyActivity, index: number): GradedActivity => {
  const topicSlug = slug(activity.topic);
  const skillId = `${grade}-${subject}-${topicSlug}`;
  const previousTopic = index >= 3 ? legacyQuestionBank[legacyBandForGrade(grade)][subject][index - 3]?.topic : undefined;
  return {
    ...activity,
    id: `grade-${grade.toLowerCase()}-${subject}-${topicSlug}-${index % 3 + 1}`,
    grade,
    prompt: `At ${gradeContexts[grade]}, ${lowerFirst(activity.prompt)}`,
    skillId,
    skillDescription: `${activity.topic}: ${curriculumMap[grade][subject][Math.floor(index / 3) % curriculumMap[grade][subject].length]}.`,
    assessmentEligible: gradeNumber(grade) <= 8,
    prerequisiteSkillIds: previousTopic && activity.difficulty && activity.difficulty > 1 ? [`${grade}-${subject}-${slug(previousTopic)}`] : undefined,
  };
};

const buildGradeSubject = (grade: GradeLevel, subject: Subject): GradedActivity[] => {
  const source = legacyQuestionBank[legacyBandForGrade(grade)][subject].map((activity, index) => gradeActivity(grade, subject, activity, index));
  const extensions = gradeExtensions[grade]?.[subject] ?? [];
  return extensions.length ? [...extensions, ...source.slice(0, 24 - extensions.length)] : source;
};

export const questionBank = Object.fromEntries(gradeLevels.map(({ grade }) => [grade, {
  science: buildGradeSubject(grade, 'science'),
  math: buildGradeSubject(grade, 'math'),
  english: buildGradeSubject(grade, 'english'),
}])) as Record<GradeLevel, Record<Subject, GradedActivity[]>>;

export const allActivities = (Object.values(questionBank) as Record<Subject, GradedActivity[]>[]).flatMap((bySubject) => Object.values(bySubject).flat());
